import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "../components/ui/sonner";
import LayoutTopBar from "./_components/layout/LayoutTopBar";
import { getSession } from "../lib/auth";
import UserProvider from "./_components/auth/UserProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const s = await getSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <UserProvider user={s?.user}>
            <div className="flex min-h-screen flex-col bg-white dark:bg-gray-950">
              <LayoutTopBar />
              {children}
            </div>
          </UserProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
